CREATE DATABASE `db_video` ;

CREATE TABLE `video` (
  `video_id` INT(11) NOT NULL AUTO_INCREMENT PRIMARY KEY,
  `video_name` VARCHAR(100) NOT NULL,
  `location` VARCHAR(100) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

CREATE TABLE `tbl_images` (
`id` INT( 11 ) NOT NULL AUTO_INCREMENT PRIMARY KEY ,
`name` VARCHAR( 100 ) NOT NULL 
) ENGINE = INNODB DEFAULT CHARSET = latin1